-- This file contains the initial data to seed the database.
-- The placeholder {{ADMIN_PASSWORD_HASH}} will be replaced by a secure hash
-- generated by the application at runtime.

-- Insert the default administrator
WITH new_admin AS (
    INSERT INTO admins (name, email, password_hash, can_create_admins)
    VALUES ('José Angel Iván Rubianes Silva', 'angelivan34@gmail.com', '{{ADMIN_PASSWORD_HASH}}', TRUE)
    ON CONFLICT (email) DO NOTHING
    RETURNING id
)
-- Insert the settings for the default administrator
INSERT INTO admin_settings (admin_id)
SELECT id FROM new_admin
ON CONFLICT (admin_id) DO NOTHING;
